// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOoWut7JNsl-wJWCY9m7MMc8Hdk79rxiE',
    appId: '1:328341724561:web:b2fd2e5503fe8450370e30',
    messagingSenderId: '328341724561',
    projectId: 'testting-83916',
    authDomain: 'testting-83916.firebaseapp.com',
    storageBucket: 'testting-83916.appspot.com',
    measurementId: 'G-Z9R3NHWKZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWyNx9x-lR_9ASbH81fsuzLGu0PnPxHo',
    appId: '1:328341724561:android:eaec9e7add5212dc370e30',
    messagingSenderId: '328341724561',
    projectId: 'testting-83916',
    storageBucket: 'testting-83916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQIIVcTi0Znu-qoGDm4fcYChBrZlKAp20',
    appId: '1:328341724561:ios:0f40c3c39d669a64370e30',
    messagingSenderId: '328341724561',
    projectId: 'testting-83916',
    storageBucket: 'testting-83916.appspot.com',
    iosBundleId: 'com.example.solutionChallege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQIIVcTi0Znu-qoGDm4fcYChBrZlKAp20',
    appId: '1:328341724561:ios:8094f24a0d4c6f38370e30',
    messagingSenderId: '328341724561',
    projectId: 'testting-83916',
    storageBucket: 'testting-83916.appspot.com',
    iosBundleId: 'com.example.solutionChallege.RunnerTests',
  );
}
